name: 'Deploy - $(workload)'

variables:
- template: /Modules/ARM/.global/global.variables.yml@AZ-SERVICES
- name: workload
  value: 'AZ-US-E-DEV-FLEXAPP'
- name: parametersPath
  value: AZ-USA-LZ/AZ-USA-LZ-DEV-SUB-01/AZ-US-E-DEV-FLEXAPP
- name: location
  value: 'East US'
- name: serviceConnection
  value: 'AZ-USA-LZ-DEV-SUB-01-SVC'

parameters:
- name: enablePostDeployment
  displayName: Execute post-deployment
  type: boolean
  default: true  

trigger:
  batch: true
  branches:
    include:
    - main
  paths:
    include:
    - AZ-USA-LZ/AZ-USA-LZ-DEV-SUB-01/AZ-US-E-DEV-FLEXAPP/*

resources:
  repositories:
  - repository: AZ-SERVICES
    type: git
    ref: 'refs/heads/main'
    name: 'AZ-SERVICES'

stages:
- stage: Validation
  jobs:
  - template: /Modules/ARM/.global/PipelineTemplates/pipeline.jobs.validate.yml@AZ-SERVICES
    parameters:
      moduleName: ResourceGroup
      modulePath: $(modulesPath)/ResourceGroup
      deploymentBlocks:
      - path: $(parametersPath)/ResourceGroup/parameters.json
        resourceGroupName: AZ-US-E-DEV-FLEXAPP-RG-01
      checkoutRepositories:
      - AZ-SERVICES

  - template: /Modules/ARM/.global/PipelineTemplates/pipeline.jobs.validate.yml@AZ-SERVICES
    parameters:
      moduleName: VirtualMachines
      modulePath: $(modulesPath)/VirtualMachines
      deploymentBlocks:
      - path: $(parametersPath)/VirtualMachines/parameters.json
        resourceGroupName: AZ-US-E-DEV-FLEXAPP-RG-01
      checkoutRepositories:
      - AZ-SERVICES


- stage: Approval
  jobs:
  - job: waitForValidation
    displayName: Wait for external validation
    pool: server
    timeoutInMinutes: 4320
    steps:
    - task: ManualValidation@0
      timeoutInMinutes: 4320

- stage: Deploy
  jobs:
  - template: /Modules/ARM/.global/PipelineTemplates/pipeline.jobs.deploy.yml@AZ-SERVICES
    parameters:
      moduleName: ResourceGroup
      modulePath: $(modulesPath)/ResourceGroup
      deploymentBlocks:
      - path: $(parametersPath)/ResourceGroup/parameters.json
        resourceGroupName: AZ-US-E-DEV-FLEXAPP-RG-01
        jobName: DeployResourceGroup
      checkoutRepositories:
      - AZ-SERVICES

  - template: /Modules/ARM/.global/PipelineTemplates/pipeline.jobs.deploy.yml@AZ-SERVICES
    parameters:
      moduleName: VirtualMachines
      modulePath: $(modulesPath)/VirtualMachines
      deploymentBlocks:
      - path: $(parametersPath)/VirtualMachines/parameters.json
        resourceGroupName: AZ-US-E-DEV-FLEXAPP-RG-01
        jobName: DeployVirtualMachines
      checkoutRepositories:
      - AZ-SERVICES
      dependsOn:
      - DeployResourceGroup  

- stage: PostDeployment
  dependsOn:
  - Deploy
  condition: and(succeeded(), eq( '${{ parameters.enablePostDeployment }}', 'true'))
  jobs:
  - template: /Modules/ARM/VirtualMachines/Pipeline/pipeline.jobs.post.staticip.yml@AZ-SERVICES 
    parameters:
      deploymentBlocks:
      - resourceGroupName: AZ-US-E-DEV-FLEXAPP-RG-01
        virtualMachineName: SWIUSEAFLXD01
    
